services:
  database_prisma:
    image: postgres:latest
    container_name: dev-prisma-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prisma
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: dev-prisma-server
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_prisma
    depends_on:
      - database_prisma
  
volumes:
  pgdata: 
    driver: local